package com.cdu.dao;

import com.cdu.bean.GoodsType;

public interface GoodsTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_type
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    int deleteByPrimaryKey(Integer goodsTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_type
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    int insert(GoodsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_type
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    int insertSelective(GoodsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_type
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    GoodsType selectByPrimaryKey(Integer goodsTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_type
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    int updateByPrimaryKeySelective(GoodsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_type
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    int updateByPrimaryKey(GoodsType record);
}