package com.cdu.dao;

import com.cdu.bean.Photo;

public interface PhotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    int deleteByPrimaryKey(Integer photoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    int insert(Photo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    int insertSelective(Photo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    Photo selectByPrimaryKey(Integer photoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    int updateByPrimaryKeySelective(Photo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    int updateByPrimaryKey(Photo record);
}