package com.cdu.dao;

import com.cdu.bean.Standard;

public interface StandardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_standard
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    int deleteByPrimaryKey(Integer standardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_standard
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    int insert(Standard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_standard
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    int insertSelective(Standard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_standard
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    Standard selectByPrimaryKey(Integer standardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_standard
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    int updateByPrimaryKeySelective(Standard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_standard
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    int updateByPrimaryKey(Standard record);
}