package com.cdu.bean;

public class GoodsType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_type.goods_type_id
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    private Integer goodsTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_type.goods_type_name
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    private String goodsTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_type.goods_type_logo
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    private String goodsTypeLogo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_type.goods_type_id
     *
     * @return the value of tb_goods_type.goods_type_id
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    public Integer getGoodsTypeId() {
        return goodsTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_type.goods_type_id
     *
     * @param goodsTypeId the value for tb_goods_type.goods_type_id
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    public void setGoodsTypeId(Integer goodsTypeId) {
        this.goodsTypeId = goodsTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_type.goods_type_name
     *
     * @return the value of tb_goods_type.goods_type_name
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    public String getGoodsTypeName() {
        return goodsTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_type.goods_type_name
     *
     * @param goodsTypeName the value for tb_goods_type.goods_type_name
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    public void setGoodsTypeName(String goodsTypeName) {
        this.goodsTypeName = goodsTypeName == null ? null : goodsTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_type.goods_type_logo
     *
     * @return the value of tb_goods_type.goods_type_logo
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    public String getGoodsTypeLogo() {
        return goodsTypeLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_type.goods_type_logo
     *
     * @param goodsTypeLogo the value for tb_goods_type.goods_type_logo
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    public void setGoodsTypeLogo(String goodsTypeLogo) {
        this.goodsTypeLogo = goodsTypeLogo == null ? null : goodsTypeLogo.trim();
    }
}