package com.cdu.bean;

public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goods_id
     *
     * @mbggenerated Mon Jun 19 15:18:07 CST 2017
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goods_name
     *
     * @mbggenerated Mon Jun 19 15:18:07 CST 2017
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goods_price
     *
     * @mbggenerated Mon Jun 19 15:18:07 CST 2017
     */
    private Double goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goods_price2
     *
     * @mbggenerated Mon Jun 19 15:18:07 CST 2017
     */
    private String goodsPrice2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goods_type
     *
     * @mbggenerated Mon Jun 19 15:18:07 CST 2017
     */
    private Integer goodsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goods_intro
     *
     * @mbggenerated Mon Jun 19 15:18:07 CST 2017
     */
    private String goodsIntro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.goods_id
     *
     * @return the value of tb_goods.goods_id
     *
     * @mbggenerated Mon Jun 19 15:18:07 CST 2017
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.goods_id
     *
     * @param goodsId the value for tb_goods.goods_id
     *
     * @mbggenerated Mon Jun 19 15:18:07 CST 2017
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.goods_name
     *
     * @return the value of tb_goods.goods_name
     *
     * @mbggenerated Mon Jun 19 15:18:07 CST 2017
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.goods_name
     *
     * @param goodsName the value for tb_goods.goods_name
     *
     * @mbggenerated Mon Jun 19 15:18:07 CST 2017
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.goods_price
     *
     * @return the value of tb_goods.goods_price
     *
     * @mbggenerated Mon Jun 19 15:18:07 CST 2017
     */
    public Double getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.goods_price
     *
     * @param goodsPrice the value for tb_goods.goods_price
     *
     * @mbggenerated Mon Jun 19 15:18:07 CST 2017
     */
    public void setGoodsPrice(Double goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.goods_price2
     *
     * @return the value of tb_goods.goods_price2
     *
     * @mbggenerated Mon Jun 19 15:18:07 CST 2017
     */
    public String getGoodsPrice2() {
        return goodsPrice2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.goods_price2
     *
     * @param goodsPrice2 the value for tb_goods.goods_price2
     *
     * @mbggenerated Mon Jun 19 15:18:07 CST 2017
     */
    public void setGoodsPrice2(String goodsPrice2) {
        this.goodsPrice2 = goodsPrice2 == null ? null : goodsPrice2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.goods_type
     *
     * @return the value of tb_goods.goods_type
     *
     * @mbggenerated Mon Jun 19 15:18:07 CST 2017
     */
    public Integer getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.goods_type
     *
     * @param goodsType the value for tb_goods.goods_type
     *
     * @mbggenerated Mon Jun 19 15:18:07 CST 2017
     */
    public void setGoodsType(Integer goodsType) {
        this.goodsType = goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.goods_intro
     *
     * @return the value of tb_goods.goods_intro
     *
     * @mbggenerated Mon Jun 19 15:18:07 CST 2017
     */
    public String getGoodsIntro() {
        return goodsIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.goods_intro
     *
     * @param goodsIntro the value for tb_goods.goods_intro
     *
     * @mbggenerated Mon Jun 19 15:18:07 CST 2017
     */
    public void setGoodsIntro(String goodsIntro) {
        this.goodsIntro = goodsIntro == null ? null : goodsIntro.trim();
    }
}