package com.cdu.bean;

public class Photo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_photo.photo_id
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    private Integer photoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_photo.photo_file
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    private String photoFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_photo.photo_goods
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    private Integer photoGoods;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_photo.photo_id
     *
     * @return the value of tb_photo.photo_id
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    public Integer getPhotoId() {
        return photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_photo.photo_id
     *
     * @param photoId the value for tb_photo.photo_id
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    public void setPhotoId(Integer photoId) {
        this.photoId = photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_photo.photo_file
     *
     * @return the value of tb_photo.photo_file
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    public String getPhotoFile() {
        return photoFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_photo.photo_file
     *
     * @param photoFile the value for tb_photo.photo_file
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    public void setPhotoFile(String photoFile) {
        this.photoFile = photoFile == null ? null : photoFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_photo.photo_goods
     *
     * @return the value of tb_photo.photo_goods
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    public Integer getPhotoGoods() {
        return photoGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_photo.photo_goods
     *
     * @param photoGoods the value for tb_photo.photo_goods
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    public void setPhotoGoods(Integer photoGoods) {
        this.photoGoods = photoGoods;
    }
}