package com.cdu.bean;

public class Standard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_standard.standard_id
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    private Integer standardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_standard.standard_color
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    private String standardColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_standard.standard_color_logo
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    private String standardColorLogo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_standard.standard_size
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    private String standardSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_standard.standard_num
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    private Integer standardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_standard.standard_goods
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    private Integer standardGoods;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_standard.standard_id
     *
     * @return the value of tb_standard.standard_id
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    public Integer getStandardId() {
        return standardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_standard.standard_id
     *
     * @param standardId the value for tb_standard.standard_id
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    public void setStandardId(Integer standardId) {
        this.standardId = standardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_standard.standard_color
     *
     * @return the value of tb_standard.standard_color
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    public String getStandardColor() {
        return standardColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_standard.standard_color
     *
     * @param standardColor the value for tb_standard.standard_color
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    public void setStandardColor(String standardColor) {
        this.standardColor = standardColor == null ? null : standardColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_standard.standard_color_logo
     *
     * @return the value of tb_standard.standard_color_logo
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    public String getStandardColorLogo() {
        return standardColorLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_standard.standard_color_logo
     *
     * @param standardColorLogo the value for tb_standard.standard_color_logo
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    public void setStandardColorLogo(String standardColorLogo) {
        this.standardColorLogo = standardColorLogo == null ? null : standardColorLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_standard.standard_size
     *
     * @return the value of tb_standard.standard_size
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    public String getStandardSize() {
        return standardSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_standard.standard_size
     *
     * @param standardSize the value for tb_standard.standard_size
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    public void setStandardSize(String standardSize) {
        this.standardSize = standardSize == null ? null : standardSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_standard.standard_num
     *
     * @return the value of tb_standard.standard_num
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    public Integer getStandardNum() {
        return standardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_standard.standard_num
     *
     * @param standardNum the value for tb_standard.standard_num
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    public void setStandardNum(Integer standardNum) {
        this.standardNum = standardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_standard.standard_goods
     *
     * @return the value of tb_standard.standard_goods
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    public Integer getStandardGoods() {
        return standardGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_standard.standard_goods
     *
     * @param standardGoods the value for tb_standard.standard_goods
     *
     * @mbggenerated Mon Jun 19 15:02:46 CST 2017
     */
    public void setStandardGoods(Integer standardGoods) {
        this.standardGoods = standardGoods;
    }
}